security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_register:
            pattern: ^/register
            anonymous: true

        api_password_reset:
            pattern: ^/password/reset
            anonymous: true

        api_doc:
            pattern: ^/api
            anonymous: true

        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path:               /login
                require_previous_session: false
                # username_parameter:       username
                # password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/login$,           roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/reset,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: (/edit)$,              roles: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/,                 role: IS_AUTHENTICATED_FULLY }